INSERT INTO fraschina_2024.distribucions (
    id, 
    clisg_id, 
    cliCDant_id, 
    razonsocial, 
    nomfantasia, 
    dire_calle_id, 
    dire_nro, 
    dire_obs, 
    codpost, 
    barrio_id, 
    zona_id, 
    telefono, 
    fax, 
    cuit, 
    fac_imp, 
    municipio_id, 
    marcas, 
    info, 
    contacto_id, 
    horario, 
    objetivos, 
    comentarios, 
    fechagira, 
    rubro_id, 
    tamanio_id, 
    modo_id, 
    localidad_id, 
    correo, 
    piso, 
    dpto, 
    desde, 
    hasta, 
    lunes, 
    sabado, 
    productos_id, 
    veraz_id, 
    estado_id, 
    obsrecep, 
    desde1, 
    hasta1, 
    auto, 
    productoCDA, 
    cobro_id, 
    tcobro_id, 
    cobrar_id, 
    status, 
    created_at, 
    updated_at
)
SELECT 
    Idcliente AS id, 
    IdcliSG AS clisg_id, 
    `Idcli-CDanterior` AS cliCDant_id,  -- Usamos comillas invertidas aquí
    RazonSocial AS razonsocial, 
    NomFantasia AS nomfantasia, 
    dire_calle AS dire_calle_id, 
    dire_nro AS dire_nro, 
    dire_obs AS dire_obs, 
    codpos AS codpost, 
    Idbarrio AS barrio_id, 
    Zona AS zona_id, 
    Telefono AS telefono, 
    Fax AS fax, 
    CUIT AS cuit, 
    fac_imp AS fac_imp, 
    IdMunicipio AS municipio_id, 
    INFOenParticular AS marcas, 
    Info AS info, 
    Contacto AS contacto_id, 
    Horario AS horario, 
    Objetivos AS objetivos, 
    Comentarios AS comentarios, 
    FechaGira AS fechagira, 
    rubro AS rubro_id, 
    tamanio AS tamanio_id, 
    modo AS modo_id, 
    IdLocalidad AS localidad_id, 
    correo AS correo, 
    piso AS piso, 
    dpto AS dpto, 
    desde AS desde, 
    hasta AS hasta, 
    lunes AS lunes, 
    sabado AS sabado, 
    productos AS productos_id, 
    Idveraz AS veraz_id, 
    Idestado AS estado_id, 
    obsRecep AS obsrecep, 
    desde1 AS desde1, 
    hasta1 AS hasta1, 
    auto AS auto, 
    productCDA AS productoCDA, 
    cobro AS cobro_id, 
    tcobro AS tcobro_id, 
    cobrar AS cobrar_id, 
    'A' AS status, 
    CURRENT_TIMESTAMP AS created_at, 
    CURRENT_TIMESTAMP AS updated_at
FROM 
    fraschin_backup.clientesdistribucion
WHERE 
    Idcliente IS NOT NULL;
