INSERT INTO
    fraschina_2024.representacions (
        razonsocial,
        dire_calle,
        dire_nro,
        piso,
        codpost,
        dire_obs,
        telefono,
        fax,
        cuit,
        excenciones,
        iva_id,
        marcas,
        info,
        contacto,
        horario,
        objetivos,
        comentarios,
        fechagira,
        correo,
        dpto,
        barrio_id,
        localidad_id,
        zona_id,
        municipio_id
    )
SELECT
    RazonSocial,
    dire_calle,
    dire_nro,
    piso,
    codpos,
    dire_obs,
    Telefono,
    Fax,
    CUIT,
    Excenciones,
    Idiva,
    NULL AS marcas, -- Asumiendo que esta columna no está en clientes
    Info,
    Contacto,
    Horario,
    Objetivos,
    Comentarios,
    FechaGira,
    correo,
    dpto,
    Idbarrio AS barrio_id,
    Idlocalidad AS localidad_id,
    Zona AS zona_id,
    IdMunicipio AS municipio_id
FROM fraschin_backup.clientes;